# Generated by Django 4.0.2 on 2022-02-04 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NFT_GEN', '0002_image_rarity_projectdesc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectdesc',
            name='user',
        ),
    ]
