# Generated by Django 4.0.2 on 2022-02-05 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NFT_GEN', '0004_projectdesc_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectdesc',
            name='total',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
