# Generated by Django 4.0.2 on 2022-02-06 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NFT_GEN', '0005_alter_projectdesc_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectdesc',
            name='img_hash',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='projectdesc',
            name='meta_hash',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
