# Generated by Django 4.0.2 on 2022-02-06 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NFT_GEN', '0006_projectdesc_img_hash_projectdesc_meta_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='layersmodel',
            name='img_num',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
    ]
