# Generated by Django 4.0.2 on 2022-02-06 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NFT_GEN', '0007_layersmodel_img_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectdesc',
            name='stats',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
