# Generated by Django 4.0.2 on 2022-02-06 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NFT_GEN', '0008_projectdesc_stats'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectdesc',
            name='stats',
            field=models.TextField(blank=True, null=True),
        ),
    ]
