# Generated by Django 4.0.2 on 2022-02-06 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NFT_GEN', '0010_archivedproject'),
    ]

    operations = [
        migrations.AddField(
            model_name='archivedproject',
            name='proj_desc',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectdesc',
            name='proj_desc',
            field=models.TextField(blank=True, null=True),
        ),
    ]
